from .defineWord import DefineWord
from .getNews import GetNews
from .getWeatherForecast import GetWeatherForecast
from .googleSearch import GoogleSearch
from .playYoutubeVid import PlayYoutubeVideo
from .shutDownSystem import ShutdownSystem
from .startOfflineMusic import StartOfflineMusic
from .stopOfflineMusic import StopOfflineMusic
from .stopProgram import StopProgram
from .tellAJoke import TellAJoke
from .tellTime import TellTime
from .wikiSearch import WikiSearch
from .default import DefaultCommand